// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_appsync_graphqlEndpoint:
    "https://nm5b7zxtarf7fnhw7cu36wcv2u.appsync-api.ap-southeast-2.amazonaws.com/graphql",
  aws_appsync_region: "ap-southeast-2",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-gst3fppsgvatfldablfhkux66m"
};

export default awsmobile;
